apiVersion: apps/v1
kind: Deployment
metadata:
  name: e6e-deployment
  labels:
    app: e6e
spec:
  selector:
    matchLabels:
      app: e6e
  template:
    metadata:
      labels:
        app: e6e
    spec:
      containers:
      - name: e6e
        image: localhost:32000/e6e:%TIMESTAMP%
        ports:
        - containerPort: 8000