apiVersion: apps/v1
kind: Deployment
metadata:
  name: urproj-deployment
  namespace: e6e
  labels:
    app: urproj
spec:
  selector:
    matchLabels:
      app: urproj
  template:
    metadata:
      labels:
        app: urproj
    spec:
      containers:
        - name: urproj
          image: localhost:32000/urproj:%TIMESTAMP%
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "30m"
              memory: "200Mi"
