apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-prd-deployment
  labels:
    app: example
spec:
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
        - name: example
          image: localhost:32000/example:%TIMESTAMP%
          ports:
            - containerPort: 8000
          resources:
          limits:
            cpu: "30m"
            memory: "200Mi"
