apiVersion: apps/v1
kind: Deployment
metadata:
  name: urproj-e2e-deployment
  namespace: e6e
  labels:
    app: urproj-e2e
spec:
  selector:
    matchLabels:
      app: urproj-e2e
  template:
    metadata:
      labels:
        app: urproj-e2e
    spec:
      volumes:
        - name: coverage-file
          emptyDir: {}
      containers:
        - name: urproj-e2e
          image: localhost:32000/urproj-e2e:%TIMESTAMP%
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: coverage-file
              mountPath: /tmp
          resources:
            limits:
              cpu: "30m"
              memory: "200Mi"
        - name: ftr
          image: localhost:32000/ftr:%TIMESTAMP%
          volumeMounts:
            - name: coverage-file
              mountPath: /tmp
          resources:
            limits:
              cpu: "30m"
              memory: "200Mi"
