apiVersion: apps/v1
kind: Deployment
metadata:
  name: e6e-e2e-deployment
  labels:
    app: e6e-e2e
spec:
  selector:
    matchLabels:
      app: e6e-e2e
  template:
    metadata:
      labels:
        app: e6e-e2e
    spec:
      containers:
      - name: e6e-e2e
        image: localhost:32000/e6e-e2e:1649792738
        ports:
        - containerPort: 8001