name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # - name: Login to GitHub Container Registry
    #   uses: docker/login-action@v1
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and publish the PRODUCTION Docker image
      run: docker image build --file go/e6e/Dockerfile -t e6e go/e6e

    - name: Build and publish the E2E TESTING Docker image
      run: docker image build --file go/e6e/Dockerfile -t e6e-e2e --target e2e go/e6e

    - name: Build and publish the COVERAGE REPORTER Docker image
      run: docker image build --file go/ftr/Dockerfile -t ftr go/ftr
